name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Add labels based on size
        run: |
          ./add-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}