# set labels on Pull-Requests based on size of changes
# size is compared form first to last commit in the pull request
name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  label-changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == 'true'
    permissions:
      pull-requests: write
    steps:
      - name: Check changes and label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGES=$((${{github.event.pull_request.additions}} + ${{github.event.pull_request.deletions}}))
          echo "Changes Made: $CHANGES"

          MINIMAL_THRESHOLD=50
          SMALL_THRESHOLD=100
          MODERATE_THRESHOLD=300

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          DELETE_LABELS=("v: minimal" "v: small" "v: moderate" "v: large")

          if [ "$CHANGES" -le "$MINIMAL_THRESHOLD" ]; then
            LABEL="v: minimal"
          elif [ "$CHANGES" -le "$SMALL_THRESHOLD" ]; then
            LABEL="v: small"
          elif [ "$CHANGES" -le "$MODERATE_THRESHOLD" ]; then
            LABEL="v: moderate"
          else
            LABEL="v: large"
          fi

          DELETE_LABELS=("${DELETE_LABELS[@]//${LABEL}}")

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"

          for DELETE_LABEL in "${DELETE_LABELS[@]}"; do
              ENCODED_LABEL=$(echo "$DELETE_LABEL" | sed 's/ /%20/g')
              curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$ENCODED_LABEL"
          done
