name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Add labels based on size
        run: |
          git fetch origin ${{ github.base_ref }}
          echo $(${{ steps.changed-files.outputs.all_changed_files }})
          CHANGES=$(git diff --ignore-all-space ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          # permision to access the add-labels-pr.sh script
          chmod +x .github/workflows/add-labels.sh
          .github/workflows/add-labels.sh

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMALL_THRESHOLD: ${{vars.SMALL_THRESHOLD}}
          MODERATE_THRESHOLD: ${{vars.MODERATE_THRESHOLD}}
          LARGE_THRESHOLD: ${{vars.LARGE_THRESHOLD}}
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}