# set labels on Pull-Requests based on size of changes
# size is compared form firt to last commit in the pull request

name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get pull request diff
        id: get-diff
        run: |
          diff_url="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/diff"
          diff_data=$(curl -sS -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $diff_url)
          echo "::set-output name=diff::${diff_data}"
  
      - name: Extract added lines
        id: extract-lines
        run: |
          diff_data="${{ steps.get-diff.outputs.diff }}"
          added_lines=$(echo "$diff_data" | jq -r '.[] | select(.status == "added") | .content')
          echo "::set-output name=added_lines::${added_lines}"
  
      - name: Display added lines
        run: |
          added_lines="${{ steps.extract-lines.outputs.added_lines }}"
          echo "Added Lines:"
          echo "$added_lines"
      - name: Check changes and label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          diff_data="${{ steps.get-diff.outputs.diff }}"
          echo "Pull Request Diff:"
          echo "$diff_data"
          CHANGES=$((${{github.event.pull_request.additions}} + ${{github.event.pull_request.deletions}}))
          echo "Changed files: $CHANGES"

          THRESHOLD=100

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          if [ "$CHANGES" -le "$THRESHOLD" ]; then
            LABEL="tiny"
            DELETE_LABEL="huge"
          else
            LABEL="huge"
            DELETE_LABEL="tiny"
          fi

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"
          curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$DELETE_LABEL"
