name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sha: ${{ github.event.pull_request.base.sha }}

      - name: Check changes and label
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGES=$(git diff --ignore-all-space ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          CHANGES=$(echo "$CHANGES" | grep -E '^[+\-]' | grep -vE '^\+\+\+|^\-\-\-')

          # ignore blank lines
          CHANGES=$(echo "$CHANGES" | grep -vE '^[\+\-]\s*$')

          # count total no of lines
          CHANGES=$(echo "$CHANGES" | wc -l)

          echo "CHANGES MADE: $CHANGES"

          MINIMAL_THRESHOLD=50

          SMALL_THRESHOLD=100
          MODERATE_THRESHOLD=300

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          DELETE_LABELS=("v: minimal" "v: small" "v: moderate" "v: large")

          if [ "$CHANGES" -le "$MINIMAL_THRESHOLD" ]; then
            LABEL="v: minimal"
          elif [ "$CHANGES" -le "$SMALL_THRESHOLD" ]; then
            LABEL="v: small"
          elif [ "$CHANGES" -le "$MODERATE_THRESHOLD" ]; then
            LABEL="v: moderate"
          else
            LABEL="v: large"
          fi

          DELETE_LABELS=("${DELETE_LABELS[@]//${LABEL}}")

          echo "Adding label: $LABEL"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $AUTH_HEADER" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"labels\":[\"$LABEL\"]}" "$API_URL" > /dev/null

          for DELETE_LABEL in "${DELETE_LABELS[@]}"; do
              # encode labels for having space
              ENCODED_LABEL=$(echo "$DELETE_LABEL" | sed 's/ /%20/g')

          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $AUTH_HEADER" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $API_URL/$ENCODED_LABEL" > /dev/null
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}