name: Label Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-changes:
    if: "!github.event.pull_request.draft"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check changes and label
        run: |
          CHANGES=$(git diff --numstat ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }})
          echo "Changed files: $CHANGES"

          TINY_THRESHOLD=50
          echo $CHANGES
          echo !github.event.pull_request.draft

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          if [ $(echo "$CHANGES" | wc -l) -le $TINY_THRESHOLD ]; then
            echo "Adding label: tiny"
            curl -X POST -H "$AUTH_HEADER" -d '{"labels":["tiny"]}' "$API_URL"
          else
            echo "Adding label: huge"
            curl -X POST -H "$AUTH_HEADER" -d '{"labels":["huge"]}' "$API_URL"
          fi
