name: Label Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check changes and label
        run: |
          FIRST_COMMIT=$(git rev-list --max-parents=0 $BASE_COMMIT)

          CHANGES=$(git diff --stat ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | awk '{changes = strtonum($4) + strtonum($6)} END {print changes}')
          echo "Changed files: $CHANGES"

          TINY_THRESHOLD=50

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          if [ "$CHANGES" -le "$TINY_THRESHOLD" ]; then
            LABEL="tiny"
            DELETE_LABEL="huge"
          else
            LABEL="huge"
            DELETE_LABEL="tiny"
          fi

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"
          curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$DELETE_LABEL"
