name: Size Labeler/Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changes and label
        run: |
          CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '^[+\-]' | grep -vE '^\+\+\+|^\-\-\-' | wc -l )
          echo $CHANGES

          SMALL_THRESHOLD=50
          MODERATE_THRESHOLD=100
          LARGE_THRESHOLD=300

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          DELETE_LABELS=("v: minimal" "v: small" "v: moderate" "v: large")

          if [ "$CHANGES" -gt "$LARGE_THRESHOLD" ]; then
            LABEL="v: large"
          elif [ "$CHANGES" -gt "$MODERATE_THRESHOLD" ]; then
            LABEL="v: moderate"
          elif [ "$CHANGES" -gt "$SMALL_THRESHOLD" ]; then
            LABEL="v: small"
          else
            LABEL="v: minimal"
          fi

          DELETE_LABELS=("${DELETE_LABELS[@]//${LABEL}}")

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"

          for DELETE_LABEL in "${DELETE_LABELS[@]}"; do
              ENCODED_LABEL=$(echo "$DELETE_LABEL" | sed 's/ /%20/g')
              curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$ENCODED_LABEL"
          done
