name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          depth: 1

      - name: Check changes and label
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          CHANGES=$(echo "$CHANGES" | grep -E '^[+\-]' | grep -vE '^\+\+\+|^\-\-\-')

          # ignore blank lines
          CHANGES=$(echo "$CHANGES" | grep -vE '^[\+\-]\s*$')

          # count total no of lines
          CHANGES=$(echo "$CHANGES" | wc -l)

          echo "CHANGES MADE: $CHANGES"

          MINIMAL_THRESHOLD=50

          SMALL_THRESHOLD=100
          MODERATE_THRESHOLD=300

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          DELETE_LABELS=("v: minimal" "v: small" "v: moderate" "v: large")

          if [ "$CHANGES" -le "$MINIMAL_THRESHOLD" ]; then
            LABEL="v: minimal"
          elif [ "$CHANGES" -le "$SMALL_THRESHOLD" ]; then
            LABEL="v: small"
          elif [ "$CHANGES" -le "$MODERATE_THRESHOLD" ]; then
            LABEL="v: moderate"
          else
            LABEL="v: large"
          fi

          DELETE_LABELS=("${DELETE_LABELS[@]//${LABEL}}")

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"

          for DELETE_LABEL in "${DELETE_LABELS[@]}"; do
              ENCODED_LABEL=$(echo "$DELETE_LABEL" | sed 's/ /%20/g')
              curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$ENCODED_LABEL"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}