# set labels on Pull-Requests based on size of changes
# size is compared form first to last commit in the pull request
name: Size Labeler/Checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - synchronize
      - ready_for_review
jobs:
  label-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check changes and label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGES=$((${{github.event.pull_request.additions}} + ${{github.event.pull_request.deletions}}))
          echo "Changes Made: $CHANGES"

          MINIMAL_THRESHOLD=50
          SMALL_THRESHOLD=100
          MODERATE_THRESHOLD=300

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          DELETE_LABELS=("v: minimal" "v: small" "v: moderate" "v: large")

          if [ "$CHANGES" -le "$MINIMAL_THRESHOLD" ]; then
            LABEL="v: minimal"
          elif [ "$CHANGES" -le "$SMALL_THRESHOLD" ]; then
            LABEL="v: small"
          elif [ "$CHANGES" -le "$MODERATE_THRESHOLD" ]; then
            LABEL="v: moderate"
          else
            LABEL="v: large"
          fi

          DELETE_LABELS=("${DELETE_LABELS[@]//${LABEL}}")

          echo "Adding label: $LABEL"
          curl -X POST -H "$AUTH_HEADER" -d "{\"labels\":[\"$LABEL\"]}" "$API_URL"

          for DELETE_LABEL in "${DELETE_LABELS[@]}"; do
              ENCODED_LABEL=$(echo "$DELETE_LABEL" | sed 's/ /%20/g')
              curl -X DELETE -H "$AUTH_HEADER" "$API_URL/$ENCODED_LABEL"
          done

          
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          LABEL_NAME=$(jq --raw-output .label.name "$GITHUB_EVENT_PATH")

          # Get the list of events related to the pull request
          EVENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/events")

          # Find the event where the label was added
          LABEL_EVENT=$(echo "$EVENTS" | jq --arg label "$LABEL_NAME" -c '.[] | select(.event == "labeled" and .label.name == $label)')

          # Extract the user who added the label
          USER_LOGIN=$(echo "$LABEL_EVENT" | jq --raw-output .actor_login)

          echo "Label '$LABEL_NAME' added to Pull Request #$PR_NUMBER by $USER_LOGIN"