name: Label Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check changes and label
        run: |
          CHANGES=$(git diff --stat ${{ github.event.before }} ${{ github.sha }} | awk '{changes = strtonum($4) + strtonum($6)} END {print changes}')
          echo "Changed files: $CHANGES"

          TINY_THRESHOLD=50

          PR_NUMBER="${{ github.event.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          if [ $CHANGES -le $TINY_THRESHOLD ]; then
            echo "Adding label: tiny"
            curl -X POST -H "$AUTH_HEADER" -d '{"labels":["tiny"]}' "$API_URL"
            curl -X DELETE -H "$AUTH_HEADER" "$API_URL/huge"
          else
            echo "Adding label: huge"
            curl -X POST -H "$AUTH_HEADER" -d '{"labels":["huge"]}' "$API_URL"
            curl -X DELETE -H "$AUTH_HEADER" "$API_URL/tiny"
          fi
