name: Count Added Non-Blank Lines

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  count_added_lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get changed files
      id: file_changes
      run: |
        # Fetch the base branch
        git fetch origin ${{ github.event.before }}
        
        # Get the list of changed files
        files_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Output the list of changed files
        echo "::set-output name=files_changed::$files_changed"

    - name: Count added non-blank lines
      run: |
        # Access the list of changed files from the previous step
        files_changed="${{ steps.file_changes.outputs.files_changed }}"

        # Loop through the changed files and run the specified command
        IFS=$'\n' # Set Internal Field Separator to newline
        for file in $files_changed; do
          echo "Counting added non-blank lines in $file"
          
          # Run the specified command on each changed file
          git show ${{ github.sha }}:"$file" | grep -vE '^\+\+\+' | grep -E '^\+' | grep -vE '^\+\s*$'
        done
