name: Count Added Non-Blank Lines

on:
  pull_request_target:
    paths:
      - '**/*'

jobs:
  count_added_lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Count added non-blank lines
      run: |
        CHANGES=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '^[+\-]' | grep -vE '^\+\+\+|^\-\-\-' | wc -l )
        echo $CHANGES
       