name: Get Lines Added/Deleted (Ignoring Blank Lines)

on:
  pull_request:

jobs:
  get_lines_changed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get lines added/deleted
      run: |
        # Fetch pull request details using GitHub API
        pr_details=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}")

        # Extract file details
        files=$(echo "$pr_details" | jq -r '.files')

        # Initialize counters for added and deleted lines
        added_lines=0
        deleted_lines=0

        # Loop through files and count lines (ignoring blank lines)
        for file in $(echo "$files" | jq -r '.[].filename'); do
          additions=$(git show ${{ github.sha }}:"$file" | grep -E '^\+' | grep -vE '^\+\s*$' | wc -l)
          deletions=$(git show ${{ github.event.before }}:"$file" | grep -E '^\-' | grep -vE '^\-\s*$' | wc -l)
          
          added_lines=$((added_lines + additions))
          deleted_lines=$((deleted_lines + deletions))
        done

        # Output the results
        echo "Added lines: $added_lines"
        echo "Deleted lines: $deleted_lines"
