name: Count Added Non-Blank Lines

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  count_added_lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Count added non-blank lines
      run: |
        git show ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} | grep -vE '^\+\+\+' | grep -E '^\+' | grep -vE '^\+\s*$'
        # Access the list of changed files from the previous step
        