name: Label and Analyze PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label_and_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add labels to pull request
        run: |
          # You can customize this script to add the desired labels based on conditions.
          # For example, add a label if the PR title contains a certain keyword.
          if [[ $(grep -i "keyword" "${{ github.event.before }}" "${{ github.event.after }}") ]]; then
            echo "Adding label to PR..."
            # Use GitHub API to add labels to the pull request.
            curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
              -d '{"labels": ["label1", "label2"]}'
          else
            echo "No label added to PR."
          fi

      - name: Analyze changes in the pull request
        run: |
          # You can use Git commands or other tools to analyze the changes in the pull request.
          echo "Analyzing changes..."
          git diff --name-only "${{ github.event.before }}" "${{ github.event.after }}"

